 begin
  DECLARE
    l_tab_exists NUMBER := 0;
    v_sting      VARCHAR2(4000);
    l_col_exists NUMBER := 0;
  BEGIN
    select count(*)
      into l_tab_exists
      from user_tab_cols
     where table_name = 'MS_APPS_ENTITY_MIGBKP';
    IF l_tab_exists = 0 THEN
      v_sting := 'CREATE TABLE MS_APPS_ENTITY_MIGBKP AS SELECT * FROM MS_APPS_ENTITY WHERE 1 = 2';
      BEGIN
        EXECUTE IMMEDIATE v_sting;
      END;
      v_sting := 'ALTER TABLE MS_APPS_ENTITY_MIGBKP ADD (ENTRY_DATE DATE)';
      BEGIN
        EXECUTE IMMEDIATE v_sting;
      END;
    ELSE
      SELECT count(*)
        into l_col_exists
        FROM USER_TAB_COLS
       WHERE TABLE_NAME = 'MS_APPS_ENTITY_MIGBKP'
         AND COLUMN_NAME = 'ENTRY_DATE';
      IF l_col_exists = 0 THEN
        v_sting := 'ALTER TABLE MS_APPS_ENTITY_MIGBKP ADD (ENTRY_DATE DATE)';
        BEGIN
          EXECUTE IMMEDIATE v_sting;
        END;
      END IF;
    END IF;
  EXCEPTIOn
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('MS_APPS_ENTITY_MIGBKP TABLE CREATION FAILS');
      NULL;
  END;

  DECLARE
    l_tab_exists      NUMBER := 0;
    v_sting           VARCHAR2(4000);
    l_col_exists      NUMBER := 0;
    l_tab_exists_comp NUMBER := 0;
    l_col_exists_comp NUMBER := 0;
  BEGIN
    select count(*)
      into l_tab_exists
      from user_tab_cols
     where table_name = 'MS_APPS_VISUAL_ENTITY_MIGBKP';
    IF l_tab_exists = 0 THEN
      v_sting := 'CREATE TABLE  MS_APPS_VISUAL_ENTITY_MIGBKP AS SELECT * FROM MS_APPS_VISUAL_ENTITY WHERE 1=2';
      BEGIN
        EXECUTE IMMEDIATE v_sting;
      END;
      v_sting := 'ALTER TABLE MS_APPS_VISUAL_ENTITY_MIGBKP ADD (ENTRY_DATE DATE)';
      BEGIN
        EXECUTE IMMEDIATE v_sting;
      END;
    ELSE
      SELECT count(*)
        into l_col_exists
        FROM USER_TAB_COLS
       WHERE TABLE_NAME = 'MS_APPS_VISUAL_ENTITY_MIGBKP'
         AND COLUMN_NAME = 'ENTRY_DATE';
      IF l_col_exists = 0 THEN
        v_sting := 'ALTER TABLE MS_APPS_VISUAL_ENTITY_MIGBKP ADD (ENTRY_DATE DATE)';
        BEGIN
          EXECUTE IMMEDIATE v_sting;
        END;
      END IF;
    END IF;
    select count(*)
      into l_tab_exists_comp
      from user_tab_cols
     where table_name = 'MS_APPS_VE_COMP_MIGBKP';
    IF l_tab_exists_comp = 0 THEN
      v_sting := 'CREATE TABLE  MS_APPS_VE_COMP_MIGBKP AS SELECT * FROM ms_apps_visual_entity_comp WHERE 1=2';
      BEGIN
        EXECUTE IMMEDIATE v_sting;
      END;
      v_sting := 'ALTER TABLE MS_APPS_VE_COMP_MIGBKP ADD (ENTRY_DATE DATE)';
      BEGIN
        EXECUTE IMMEDIATE v_sting;
      END;
    ELSE
      SELECT count(*)
        into l_col_exists_comp
        FROM USER_TAB_COLS
       WHERE TABLE_NAME = 'MS_APPS_VE_COMP_MIGBKP'
         AND COLUMN_NAME = 'ENTRY_DATE';
      IF l_col_exists_comp = 0 THEN
        v_sting := 'ALTER TABLE MS_APPS_VE_COMP_MIGBKP ADD (ENTRY_DATE DATE)';
        BEGIN
          EXECUTE IMMEDIATE v_sting;
        END;
      END IF;
    END IF;
  EXCEPTIOn
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('MS_APPS_VISUAL_ENTITY_MIGBKP or MS_APPS_VE_COMP_MIGBKP TABLE CREATION FAILS');
      NULL;
  END;

  DECLARE
    x_str            varchar2(4000);
    x_clob           clob;
    pi_xml           xmltype;
    o_error_code     number;
    po_error_message varchar2(4000);
  BEGIN
  
	DELETE FROM MS_APPS_ENTITY_MIGBKP Where DB_TABLE_NAME = 'MS_RGA_NOTIFY_USERS';
    COMMIT;
	
    INSERT INTO MS_APPS_ENTITY_MIGBKP
      (LOG_NUMBER,
       SECURITY_VIEW,
       SECURITY_VIEW_ALL,
       DEPLOYED_ON,
       SECURITY_RESTRICTION,
       SECURITY_OWNERSHIP,
       MODULE,
       INTERNAL_NAME,
       DB_TABLE_NAME,
       DISPLAY_NAME,
       DESCRIPTION,
       ICON,
       DERIVED_FROM,
       ENABLED,
       DATA_VER,
       CREATED_BY,
       CREATION_DATE,
       UPDATED_BY,
       UPDATION_DATE,
       ENTITY_DEPLOYED,
       SEQ_NO,
       PROCESS_INSTANCE_ID,
       ENTITY_VERSION,
       ENTITY_UNIQUE_ID,
       APPSTUDIO_VERSION,
       ENTRY_DATE)
      SELECT LOG_NUMBER,
             SECURITY_VIEW,
             SECURITY_VIEW_ALL,
             DEPLOYED_ON,
             SECURITY_RESTRICTION,
             SECURITY_OWNERSHIP,
             MODULE,
             INTERNAL_NAME,
             DB_TABLE_NAME,
             DISPLAY_NAME,
             DESCRIPTION,
             ICON,
             DERIVED_FROM,
             ENABLED,
             DATA_VER,
             CREATED_BY,
             CREATION_DATE,
             UPDATED_BY,
             UPDATION_DATE,
             ENTITY_DEPLOYED,
             SEQ_NO,
             PROCESS_INSTANCE_ID,
             ENTITY_VERSION,
             ENTITY_UNIQUE_ID,
             APPSTUDIO_VERSION,
             SYSDATE
        FROM MS_APPS_ENTITY
       where DB_TABLE_NAME = 'MS_RGA_NOTIFY_USERS';
    COMMIT;
  
    DELETE FROM MS_APPS_ENTITY Where DB_TABLE_NAME = 'MS_RGA_NOTIFY_USERS';
    COMMIT;
  
    DELETE FROM MS_APPS_VISUAL_ENTITY_MIGBKP Where ve_pushform_name = 'DUMMY';
    COMMIT;
  
    INSERT INTO MS_APPS_VISUAL_ENTITY_MIGBKP
      (LOG_NUMBER,
       SECURITY_EDIT,
       SECURITY_EDIT_ALL,
       SECURITY_VIEW,
       SECURITY_VIEW_ALL,
       DEPLOYED_ON,
       VE_ENABLED_FLAG,
       VE_VIEW_NAME,
       CREATED_BY,
       CREATION_DATE,
       UPDATED_BY,
       UPDATION_DATE,
       VE_VERSION,
       VE_DEPLOYED,
       SEQ_NO,
       VE_DVIEW_NAME,
       PROCESS_INSTANCE_ID,
       VE_NAME,
       VE_PUSHFORM_NAME,
       VE_TITLE,
       VE_DESCRIPTION,
       VE_MODULE,
       VE_DERIVED_FROM,
       VE_UNIQUE_ID,
       APPSTUDIO_VERSION,
       ENTRY_DATE)
      SELECT LOG_NUMBER,
             SECURITY_EDIT,
             SECURITY_EDIT_ALL,
             SECURITY_VIEW,
             SECURITY_VIEW_ALL,
             DEPLOYED_ON,
             VE_ENABLED_FLAG,
             VE_VIEW_NAME,
             CREATED_BY,
             CREATION_DATE,
             UPDATED_BY,
             UPDATION_DATE,
             VE_VERSION,
             VE_DEPLOYED,
             SEQ_NO,
             VE_DVIEW_NAME,
             PROCESS_INSTANCE_ID,
             VE_NAME,
             VE_PUSHFORM_NAME,
             VE_TITLE,
             VE_DESCRIPTION,
             VE_MODULE,
             VE_DERIVED_FROM,
             VE_UNIQUE_ID,
             APPSTUDIO_VERSION,
             SYSDATE
        FROM MS_APPS_VISUAL_ENTITY
       where ve_pushform_name = 'DUMMY';
    COMMIT;
  
    DELETE FROM MS_APPS_VISUAL_ENTITY Where ve_pushform_name = 'DUMMY';
    COMMIT;
  
	DELETE FROM MS_APPS_VE_COMP_MIGBKP Where ve_name = 'DUMMY';
    COMMIT;
  
    INSERT INTO MS_APPS_VE_COMP_MIGBKP
      (entity_name,
       ve_name,
       ENABLED_FLAG,
       PARENT_ENTITY_NAME,
       PARENT_ENTITY_MAP_COLS,
       PARENT_ENTITY_REG,
       CONTROL_FLAG,
       ENTRY_DATE)
      SELECT entity_name,
      		 ve_name,
             ENABLED_FLAG,
             PARENT_ENTITY_NAME,
             PARENT_ENTITY_MAP_COLS,
             PARENT_ENTITY_REG,
             CONTROL_FLAG,
             SYSDATE
        FROM ms_apps_visual_entity_comp
       where ve_name = 'DUMMY';
    COMMIT;
  
    DELETE FROM MS_APPS_VISUAL_ENTITY_COMP Where ve_name = 'DUMMY';
    COMMIT;
  
    DBMS_LOB.CREATETEMPORARY(lob_loc => x_clob,
                             cache   => true,
                             dur     => DBMS_LOB.SESSION);
    DBMS_LOB.OPEN(lob_loc => x_clob, open_mode => DBMS_LOB.LOB_READWRITE);
    x_str := '<DATA_OBJECT><LOG_NUMBER>279</LOG_NUMBER><SECURITY_VIEW></SECURITY_VIEW><SECURITY_VIEW_ALL></SECURITY_VIEW_ALL><DEPLOYED_ON>08-NOV-12</DEPLOYED_ON><SECURITY_RESTRICTION></SECURITY_RESTRICTION><SECURITY_OWNERSHIP></SECURITY_OWNERSHIP><MODULE>RGA</MODULE><INTERNAL_NAME>NOTIFY USERS</INTERNAL_NAME><DB_TABLE_NAME>MS_RGA_NOTIFY_USERS</DB_TABLE_NAME><DISPLAY_NAME>NOTIFY USERS</DISPLAY_NAME><DESCRIPTION>NOTIFY USERS</DESCRIPTION><ICON></ICON><DERIVED_FROM></DERIVED_FROM><ENABLED>Y</ENABLED><DATA_VER>N</DATA_VER><CREATED_BY></CREATED_BY><CREATION_DATE></CREATION_DATE><UPDATED_BY></UPDATED_BY><UPDATION_DATE></UPDATION_DATE><ENTITY_DEPLOYED>Y</ENTITY_DEPLOYED><SEQ_NO>100118</SEQ_NO><PROCESS_INSTANCE_ID>5400</PROCESS_INSTANCE_ID><ENTITY_VERSION>17</ENTITY_VERSION><ENTITY_UNIQUE_ID>100079</ENTITY_UNIQUE_ID><APPSTUDIO_VERSION>2.1</APPSTUDIO_VERSION><ATTRIBUTES><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>Y</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>1</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Object ID</ATTR_NAME><ATTR_ID>OBJECT_ID</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Object ID</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Object ID</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED';
    dbms_lob.WRITEAPPEND(x_clob, length(x_str), x_str);
    x_str := '><COLUMN_ORDER>2</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Object Name</ATTR_NAME><ATTR_ID>OBJECT_NAME</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Object Name</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Object Name</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>3</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Channel ID</ATTR_NAME><ATTR_ID>CHANNEL_ID</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Channel ID</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></A';
    dbms_lob.WRITEAPPEND(x_clob, length(x_str), x_str);
    x_str := 'TTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Channel ID</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>4</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Channel Name</ATTR_NAME><ATTR_ID>CHANNEL_NAME</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Channel Name</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Channel Name</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>5</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT>';
    dbms_lob.WRITEAPPEND(x_clob, length(x_str), x_str);
    x_str := '</PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Susb Response Id</ATTR_NAME><ATTR_ID>SUSB_RESPONSE_ID</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Susb Response Id</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Susb Response Id</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>6</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Notify Other Users</ATTR_NAME><ATTR_ID>NOTIFY_OTHER_USERS</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Notify Other Users</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Notify Other Users</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_IN';
    dbms_lob.WRITEAPPEND(x_clob, length(x_str), x_str);
    x_str := 'PUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>7</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Notification Id</ATTR_NAME><ATTR_ID>NOTIFICATION_ID</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Notification Id</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Notification Id</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>8</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUE';
    dbms_lob.WRITEAPPEND(x_clob, length(x_str), x_str);
    x_str := 'S></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Received On</ATTR_NAME><ATTR_ID>RECEIVED_ON</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Received On</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Received On</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE>null</ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>9</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT>1</DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS>i_feed_id|N</DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC>EMAIL_SUBJECT</ATTR_DFLT_INPUT_SRC><ATTR_NAME>Alert</ATTR_NAME><ATTR_ID>ALERT_TITLE</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Alert</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET>MS RGA Get Feed Body</ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Alert</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_';
    dbms_lob.WRITEAPPEND(x_clob, length(x_str), x_str);
    x_str := 'INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>3</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE>null</ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>10</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Feed Id</ATTR_NAME><ATTR_ID>FEED_DATA_ID</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Feed Id</ATTR_LABEL><ATTR_TYPE>3</ATTR_TYPE><ATTR_SIZE>10</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Feed Id</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>11</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INP';
    dbms_lob.WRITEAPPEND(x_clob, length(x_str), x_str);
    x_str := 'UT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Org Entity Id</ATTR_NAME><ATTR_ID>ORG_ENTITY_ID</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Org Entity Id</ATTR_LABEL><ATTR_TYPE>3</ATTR_TYPE><ATTR_SIZE>10</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Org Entity Id</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>12</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Custom Field 1</ATTR_NAME><ATTR_ID>CUSTOM_FIELD_1</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Custom Field 1</ATTR_LABEL><ATTR_TYPE>4</ATTR_TYPE><ATTR_SIZE></ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Custom Field 1</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRON';
    dbms_lob.WRITEAPPEND(x_clob, length(x_str), x_str);
    x_str := 'YM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>13</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Custom Field 2</ATTR_NAME><ATTR_ID>CUSTOM_FIELD_2</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Custom Field 2</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Custom Field 2</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>14</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Custom Field 3</ATTR_NAME><ATTR_ID>CUSTOM_FIELD_3</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Custom Field 3</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALID';
    dbms_lob.WRITEAPPEND(x_clob, length(x_str), x_str);
    x_str := 'ATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Custom Field 3</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>15</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Custom Field 4</ATTR_NAME><ATTR_ID>CUSTOM_FIELD_4</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Custom Field 4</ATTR_LABEL><ATTR_TYPE>3</ATTR_TYPE><ATTR_SIZE>10</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Custom Field 4</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>16</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><A';
    dbms_lob.WRITEAPPEND(x_clob, length(x_str), x_str);
    x_str := 'DVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Custom Field 5</ATTR_NAME><ATTR_ID>CUSTOM_FIELD_5</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Custom Field 5</ATTR_LABEL><ATTR_TYPE>3</ATTR_TYPE><ATTR_SIZE>10</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Custom Field 5</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM>PHN</ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>Y</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>17</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT>0</PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>Notify System Users</ATTR_NAME><ATTR_ID>NOTIFY_SYSTEM_USERS</ATTR_ID><ATTR_SOURCE>MS_RGA_NOTIFY_USERS</ATTR_SOURCE><ATTR_LABEL>Notify System Users</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET>MS RGA Get System Users</ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INF';
    dbms_lob.WRITEAPPEND(x_clob, length(x_str), x_str);
    x_str := 'OLET_FILTER><SEQ_NO>100118</SEQ_NO><ATTR_DESC>Notify System Users</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC>FULL_NAME</ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC>USER_NAME</ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_NOTIFY_USERS</ATTR_BASE_SRC><ATTR_DISP_COLUMNS>USER_NAME,FULL_NAME</ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE>null</ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>3</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE></ATTRIBUTES><REGIONS><REGION><ENTITY_DB_TABLE_NAME>MS_RGA_NOTIFY_USERS</ENTITY_DB_TABLE_NAME><REGION_NAME>PHN</REGION_NAME><REGION_ACRONYM>PHN</REGION_ACRONYM><SEQ_NO>100118</SEQ_NO><PARENT_REGION></PARENT_REGION></REGION></REGIONS></DATA_OBJECT>';
    dbms_lob.WRITEAPPEND(x_clob, length(x_str), x_str);
    pi_xml := xmltype(x_clob);
    ms_apps_dd_migrate_data.migrate_data_object(pi_xml,
                                                o_error_code,
                                                po_error_message);
    dbms_output.put_line(po_error_Message);
  EXCEPTION
    WHEN OTHERS THEN
      dbms_output.put_line('Error' || sqlerrm);
  END;
end;
