 begin

DECLARE
  l_tab_exists NUMBER := 0;
  v_sting      VARCHAR2(4000);
  l_col_exists NUMBER := 0;
BEGIN
  select count(*)
    into l_tab_exists
    from user_tab_cols
   where table_name = 'MS_APPS_ENTITY_MIGBKP';
  IF l_tab_exists = 0 THEN
    v_sting := 'CREATE TABLE MS_APPS_ENTITY_MIGBKP AS SELECT * FROM MS_APPS_ENTITY WHERE 1 = 2';
    BEGIN
     EXECUTE IMMEDIATE v_sting;
    END;
    v_sting := 'ALTER TABLE MS_APPS_ENTITY_MIGBKP ADD (ENTRY_DATE DATE)';
    BEGIN
     EXECUTE IMMEDIATE v_sting;
    END;
  ELSE  
    SELECT count(*)
      into l_col_exists FROM USER_TAB_COLS
     WHERE TABLE_NAME='MS_APPS_ENTITY_MIGBKP'
       AND COLUMN_NAME='ENTRY_DATE';
      IF l_col_exists = 0 THEN
        v_sting := 'ALTER TABLE MS_APPS_ENTITY_MIGBKP ADD (ENTRY_DATE DATE)';
        BEGIN
          EXECUTE IMMEDIATE v_sting;
        END;
      END IF;
  END IF;
EXCEPTIOn WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('MS_APPS_ENTITY_MIGBKP TABLE CREATION FAILS'); NULL; END;

DECLARE
  l_tab_exists NUMBER := 0;
  v_sting      VARCHAR2(4000);
  l_col_exists NUMBER := 0;
  l_tab_exists_comp NUMBER := 0;
  l_col_exists_comp NUMBER := 0;
BEGIN
  select count(*)
    into l_tab_exists
    from user_tab_cols
   where table_name = 'MS_APPS_VISUAL_ENTITY_MIGBKP';
  IF l_tab_exists = 0 THEN
    v_sting := 'CREATE TABLE  MS_APPS_VISUAL_ENTITY_MIGBKP AS SELECT * FROM MS_APPS_VISUAL_ENTITY WHERE 1=2';
    BEGIN
      EXECUTE IMMEDIATE v_sting;
    END;
      v_sting := 'ALTER TABLE MS_APPS_VISUAL_ENTITY_MIGBKP ADD (ENTRY_DATE DATE)';
    BEGIN
      EXECUTE IMMEDIATE v_sting;
    END;
  ELSE  
    SELECT count(*)
      into l_col_exists FROM USER_TAB_COLS
     WHERE TABLE_NAME='MS_APPS_VISUAL_ENTITY_MIGBKP'
       AND COLUMN_NAME='ENTRY_DATE';
      IF l_col_exists = 0 THEN
        v_sting := 'ALTER TABLE MS_APPS_VISUAL_ENTITY_MIGBKP ADD (ENTRY_DATE DATE)';
        BEGIN
          EXECUTE IMMEDIATE v_sting;
        END;
      END IF;  
  END IF;
  select count(*)
    into l_tab_exists_comp
    from user_tab_cols
   where table_name = 'MS_APPS_VE_COMP_MIGBKP';
  IF l_tab_exists_comp = 0 THEN
    v_sting := 'CREATE TABLE  MS_APPS_VE_COMP_MIGBKP AS SELECT * FROM ms_apps_visual_entity_comp WHERE 1=2';
    BEGIN
      EXECUTE IMMEDIATE v_sting;
    END;
      v_sting := 'ALTER TABLE MS_APPS_VE_COMP_MIGBKP ADD (ENTRY_DATE DATE)';
    BEGIN
      EXECUTE IMMEDIATE v_sting;
    END;
  ELSE  
    SELECT count(*)
      into l_col_exists_comp FROM USER_TAB_COLS
     WHERE TABLE_NAME='MS_APPS_VE_COMP_MIGBKP'
       AND COLUMN_NAME='ENTRY_DATE';
      IF l_col_exists_comp = 0 THEN
        v_sting := 'ALTER TABLE MS_APPS_VE_COMP_MIGBKP ADD (ENTRY_DATE DATE)';
        BEGIN
          EXECUTE IMMEDIATE v_sting;
        END;
      END IF;  
  END IF;
EXCEPTIOn
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('MS_APPS_VISUAL_ENTITY_MIGBKP or MS_APPS_VE_COMP_MIGBKP TABLE CREATION FAILS');
    NULL;
END;

DECLARE 
    x_str varchar2(4000);
    x_clob clob;
    pi_xml xmltype;
    o_error_code number;
    po_error_message varchar2(4000);
BEGIN  
     --Taking Backup of the MS_APPS_ENTITY
     INSERT INTO MS_APPS_ENTITY_MIGBKP(LOG_NUMBER,
     SECURITY_VIEW,SECURITY_VIEW_ALL,DEPLOYED_ON,SECURITY_RESTRICTION,SECURITY_OWNERSHIP,MODULE,
     INTERNAL_NAME,DB_TABLE_NAME,DISPLAY_NAME,DESCRIPTION,ICON,DERIVED_FROM,ENABLED,DATA_VER,
     CREATED_BY,CREATION_DATE,UPDATED_BY,UPDATION_DATE,ENTITY_DEPLOYED,SEQ_NO,PROCESS_INSTANCE_ID,
     ENTITY_VERSION,ENTITY_UNIQUE_ID,APPSTUDIO_VERSION,ENTRY_DATE) 
     SELECT LOG_NUMBER,
     SECURITY_VIEW,SECURITY_VIEW_ALL,DEPLOYED_ON,SECURITY_RESTRICTION,SECURITY_OWNERSHIP,MODULE,
     INTERNAL_NAME,DB_TABLE_NAME,DISPLAY_NAME,DESCRIPTION,ICON,DERIVED_FROM,ENABLED,DATA_VER,
     CREATED_BY,CREATION_DATE,UPDATED_BY,UPDATION_DATE,ENTITY_DEPLOYED,SEQ_NO,PROCESS_INSTANCE_ID,
     ENTITY_VERSION,ENTITY_UNIQUE_ID,APPSTUDIO_VERSION,SYSDATE
     FROM MS_APPS_ENTITY
     where DB_TABLE_NAME='MS_RGA_ATTACHMENT';
     COMMIT;
     --Delete the existing record of MS_APPS_ENTITY
     DELETE FROM MS_APPS_ENTITY Where DB_TABLE_NAME = 'MS_RGA_ATTACHMENT'; 
     COMMIT;
     --Taking Backup of the MS_APPS_VISUAL_ENTITY
     INSERT INTO MS_APPS_VISUAL_ENTITY_MIGBKP
     (LOG_NUMBER,SECURITY_EDIT,SECURITY_EDIT_ALL,SECURITY_VIEW,
     SECURITY_VIEW_ALL,DEPLOYED_ON,VE_ENABLED_FLAG,VE_VIEW_NAME,CREATED_BY,CREATION_DATE,UPDATED_BY,
     UPDATION_DATE,VE_VERSION,VE_DEPLOYED,SEQ_NO,VE_DVIEW_NAME,PROCESS_INSTANCE_ID,VE_NAME,VE_PUSHFORM_NAME,
     VE_TITLE,VE_DESCRIPTION,VE_MODULE,VE_DERIVED_FROM,VE_UNIQUE_ID,APPSTUDIO_VERSION,ENTRY_DATE)
     SELECT LOG_NUMBER,SECURITY_EDIT,SECURITY_EDIT_ALL,SECURITY_VIEW,
     SECURITY_VIEW_ALL,DEPLOYED_ON,VE_ENABLED_FLAG,VE_VIEW_NAME,CREATED_BY,CREATION_DATE,UPDATED_BY,
     UPDATION_DATE,VE_VERSION,VE_DEPLOYED,SEQ_NO,VE_DVIEW_NAME,PROCESS_INSTANCE_ID,VE_NAME,VE_PUSHFORM_NAME,
     VE_TITLE,VE_DESCRIPTION,VE_MODULE,VE_DERIVED_FROM,VE_UNIQUE_ID,APPSTUDIO_VERSION,SYSDATE 
     FROM MS_APPS_VISUAL_ENTITY
     where ve_pushform_name='DUMMY';
     COMMIT;
     --Delete the existing record of MS_APPS_VISUAL_ENTITY
     DELETE FROM MS_APPS_VISUAL_ENTITY Where ve_pushform_name = 'DUMMY'; 
     COMMIT;
     ----Taking Backup of the MS_APPS_VISUAL_ENTITY_COMP
     INSERT INTO MS_APPS_VE_COMP_MIGBKP
     (entity_name,ENABLED_FLAG,PARENT_ENTITY_NAME,PARENT_ENTITY_MAP_COLS,
     PARENT_ENTITY_REG,CONTROL_FLAG,ENTRY_DATE)
     SELECT entity_name,ENABLED_FLAG,PARENT_ENTITY_NAME,PARENT_ENTITY_MAP_COLS,PARENT_ENTITY_REG,
     CONTROL_FLAG,SYSDATE FROM ms_apps_visual_entity_comp
     where ve_name='DUMMY';
     COMMIT;
     --Delete the existing record of MS_APPS_VISUAL_ENTITY_COMP
     DELETE FROM MS_APPS_VISUAL_ENTITY_COMP Where ve_name = 'DUMMY'; 
     COMMIT;
  
           DBMS_LOB.CREATETEMPORARY(lob_loc => x_clob,
                               cache   => true, 
                               dur     => DBMS_LOB.SESSION );
             DBMS_LOB.OPEN(lob_loc    => x_clob,
                           open_mode  => DBMS_LOB.LOB_READWRITE);
    x_str := '<DATA_OBJECT><LOG_NUMBER>320</LOG_NUMBER><SECURITY_VIEW></SECURITY_VIEW><SECURITY_VIEW_ALL></SECURITY_VIEW_ALL><DEPLOYED_ON>12-DEC-12</DEPLOYED_ON><SECURITY_RESTRICTION></SECURITY_RESTRICTION><SECURITY_OWNERSHIP></SECURITY_OWNERSHIP><MODULE>RGA</MODULE><INTERNAL_NAME>ATTACHMENT</INTERNAL_NAME><DB_TABLE_NAME>MS_RGA_ATTACHMENT</DB_TABLE_NAME><DISPLAY_NAME>ATTACHMENT</DISPLAY_NAME><DESCRIPTION>ATTACHMENT</DESCRIPTION><ICON></ICON><DERIVED_FROM></DERIVED_FROM><ENABLED>Y</ENABLED><DATA_VER>N</DATA_VER><CREATED_BY></CREATED_BY><CREATION_DATE></CREATION_DATE><UPDATED_BY></UPDATED_BY><UPDATION_DATE></UPDATION_DATE><ENTITY_DEPLOYED>Y</ENTITY_DEPLOYED><SEQ_NO>100146</SEQ_NO><PROCESS_INSTANCE_ID>6776</PROCESS_INSTANCE_ID><ENTITY_VERSION>4</ENTITY_VERSION><ENTITY_UNIQUE_ID>100142</ENTITY_UNIQUE_ID><APPSTUDIO_VERSION>2.1</APPSTUDIO_VERSION><ATTRIBUTES><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>1</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>ATTACHMENT</ATTR_NAME><ATTR_ID>ATTACHMENT</ATTR_ID><ATTR_SOURCE>MS_RGA_ATTACHMENT</ATTR_SOURCE><ATTR_LABEL>ATTACHMENT</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>4000</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100146</SEQ_NO><ATTR_DESC>ATTACHMENT</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_ATTACHMENT</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>Y</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN';
     dbms_lob.WRITEAPPEND(x_clob,length(x_str),x_str);
    x_str := '_ORDER>2</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>FEED_DATA_ID</ATTR_NAME><ATTR_ID>FEED_DATA_ID</ATTR_ID><ATTR_SOURCE>MS_RGA_ATTACHMENT</ATTR_SOURCE><ATTR_LABEL>FEED_DATA_ID</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100146</SEQ_NO><ATTR_DESC>FEED_DATA_ID</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_ATTACHMENT</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>3</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>CUSTOM_FIELD1</ATTR_NAME><ATTR_ID>CUSTOM_FIELD1</ATTR_ID><ATTR_SOURCE>MS_RGA_ATTACHMENT</ATTR_SOURCE><ATTR_LABEL>CUSTOM_FIELD1</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></AT';
     dbms_lob.WRITEAPPEND(x_clob,length(x_str),x_str);
    x_str := 'TR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100146</SEQ_NO><ATTR_DESC>CUSTOM_FIELD1</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_ATTACHMENT</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>4</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT></PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>CUSTOM_FIELD2</ATTR_NAME><ATTR_ID>CUSTOM_FIELD2</ATTR_ID><ATTR_SOURCE>MS_RGA_ATTACHMENT</ATTR_SOURCE><ATTR_LABEL>CUSTOM_FIELD2</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100146</SEQ_NO><ATTR_DESC>CUSTOM_FIELD2</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_ATTACHMENT</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE><ATTRIBUTE><FILTER_PARAM_COUNT></FILTER_PARAM_COUNT><DEFAULT_FILTER_PARAM_COUNT></DEFAULT_FILTER_PARAM_COUNT><APPS_ID></APPS_ID><ATTR_REGION_ACRONYM></ATTR_REGION_ACRONYM><ATTR_PRIMARY_KEY>N</ATTR_PRIMARY_KEY><ATTR_REQUIRED>N</ATTR_REQUIRED><COLUMN_ORDER>5</COLUMN_ORDER><BASIC_SEARCH_COLUMN_ORDER></BASIC_SEARCH_COLUMN_ORDER><BASIC_SEARCH_FILTER_ORDER></BASIC_SEARCH_FILTER_ORDER><ADVANCED_SEARCH_COLUMN_ORDER></ADVANCED_SEARCH_COLUMN_ORDER><ADVANCED_SEARCH_FILTER_ORDER></ADVANCED_SEARCH_FILTER_ORDER><PARAM_COUNT>';
     dbms_lob.WRITEAPPEND(x_clob,length(x_str),x_str);
    x_str := '</PARAM_COUNT><DEFAULT_PARAM_COUNT></DEFAULT_PARAM_COUNT><INFOLET_PARAMS></INFOLET_PARAMS><DEFAULT_INFOLET_PARAMS></DEFAULT_INFOLET_PARAMS><INFOLET_PARAM_VALUES></INFOLET_PARAM_VALUES><DEFAULT_INFOLET_PARAM_VALUES></DEFAULT_INFOLET_PARAM_VALUES><INFOLET_F_PARAMS></INFOLET_F_PARAMS><DEFAULT_INFOLET_F_PARAMS></DEFAULT_INFOLET_F_PARAMS><INFOLET_F_PARAM_VALUES></INFOLET_F_PARAM_VALUES><DEFAULT_INFOLET_F_PARAM_VALUES></DEFAULT_INFOLET_F_PARAM_VALUES><ATTR_DFLT_INPUT_SRC></ATTR_DFLT_INPUT_SRC><ATTR_NAME>CUSTOM_FIELD3</ATTR_NAME><ATTR_ID>CUSTOM_FIELD3</ATTR_ID><ATTR_SOURCE>MS_RGA_ATTACHMENT</ATTR_SOURCE><ATTR_LABEL>CUSTOM_FIELD3</ATTR_LABEL><ATTR_TYPE>5</ATTR_TYPE><ATTR_SIZE>255</ATTR_SIZE><ATTR_VALIDATION_INFOLET></ATTR_VALIDATION_INFOLET><ATTR_DEFAULT_INFOLET></ATTR_DEFAULT_INFOLET><ATTR_VALIDATION_INFOLET_FILTER></ATTR_VALIDATION_INFOLET_FILTER><ATTR_DEFAULT_INFOLET_FILTER></ATTR_DEFAULT_INFOLET_FILTER><SEQ_NO>100146</SEQ_NO><ATTR_DESC>CUSTOM_FIELD3</ATTR_DESC><ATTR_HELP></ATTR_HELP><ATTR_OTHER_SETTINGS></ATTR_OTHER_SETTINGS><ATTR_DISP_INPUT_SRC></ATTR_DISP_INPUT_SRC><ATTR_STORED_INPUT_SRC></ATTR_STORED_INPUT_SRC><ATTR_BASE_SRC>MS_RGA_ATTACHMENT</ATTR_BASE_SRC><ATTR_DISP_COLUMNS></ATTR_DISP_COLUMNS><ATTRIBUTE_DFLT_INPUT_VALUE></ATTRIBUTE_DFLT_INPUT_VALUE><ATTR_INPUT_TYPE>0</ATTR_INPUT_TYPE><ATTR_D_INPUT_TYPE>0</ATTR_D_INPUT_TYPE><ATTR_INPUT_VALUE></ATTR_INPUT_VALUE></ATTRIBUTE></ATTRIBUTES><REGIONS></REGIONS></DATA_OBJECT>';
     dbms_lob.WRITEAPPEND(x_clob,length(x_str),x_str);
     pi_xml := xmltype(x_clob);
     ms_apps_dd_migrate_data.migrate_data_object(pi_xml,o_error_code , po_error_message );
     dbms_output.put_line(po_error_Message);
EXCEPTION WHEN OTHERS THEN 
         dbms_output.put_line('Error'||sqlerrm);
END;
end;
