//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.19 at 02:25:45 PM IST 
//


package com.metricstream.systemi.rga.grcobject.jaxb.requirement;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RQTType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RQTType">
 *   &lt;complexContent>
 *     &lt;extension base="{}CommonFieldsType">
 *       &lt;sequence>
 *         &lt;element name="object_level" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Parent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KeyRequirement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Section_Citation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Categories" type="{}RequirementCategories" minOccurs="0"/>
 *         &lt;element name="Type_of_Compliance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TFE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Violation_Severity_Level" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Violation_Risk_Factor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Impact_and_Penalties" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Penalties_for_Non-Compliance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Frequency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StartAfter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DueAfter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NextScheduleDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Relationships" type="{}RelationshipType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RQTType", propOrder = {
    "objectLevel",
    "parent",
    "keyRequirement",
    "sectionCitation",
    "categories",
    "typeOfCompliance",
    "tfe",
    "violationSeverityLevel",
    "violationRiskFactor",
    "tier",
    "year",
    "impactAndPenalties",
    "penaltiesForNonCompliance",
    "frequency",
    "startAfter",
    "dueAfter",
    "nextScheduleDate",
    "relationships"
})
public class RQTType
    extends CommonFieldsType
{

    @XmlElement(name = "object_level", required = true)
    protected String objectLevel;
    @XmlElement(name = "Parent")
    protected String parent;
    @XmlElement(name = "KeyRequirement")
    protected String keyRequirement;
    @XmlElement(name = "Section_Citation", required = true)
    protected String sectionCitation;
    @XmlElement(name = "Categories")
    protected RequirementCategories categories;
    @XmlElement(name = "Type_of_Compliance")
    protected String typeOfCompliance;
    @XmlElement(name = "TFE")
    protected String tfe;
    @XmlElement(name = "Violation_Severity_Level")
    protected String violationSeverityLevel;
    @XmlElement(name = "Violation_Risk_Factor")
    protected String violationRiskFactor;
    @XmlElement(name = "Tier")
    protected String tier;
    @XmlElement(name = "Year")
    protected String year;
    @XmlElement(name = "Impact_and_Penalties")
    protected String impactAndPenalties;
    @XmlElement(name = "Penalties_for_Non-Compliance")
    protected String penaltiesForNonCompliance;
    @XmlElement(name = "Frequency", required = true)
    protected String frequency;
    @XmlElement(name = "StartAfter")
    protected String startAfter;
    @XmlElement(name = "DueAfter")
    protected String dueAfter;
    @XmlElement(name = "NextScheduleDate")
    protected String nextScheduleDate;
    @XmlElement(name = "Relationships")
    protected RelationshipType relationships;

    /**
     * Gets the value of the objectLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectLevel() {
        return objectLevel;
    }

    /**
     * Sets the value of the objectLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectLevel(String value) {
        this.objectLevel = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParent(String value) {
        this.parent = value;
    }

    /**
     * Gets the value of the keyRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyRequirement() {
        return keyRequirement;
    }

    /**
     * Sets the value of the keyRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyRequirement(String value) {
        this.keyRequirement = value;
    }

    /**
     * Gets the value of the sectionCitation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSectionCitation() {
        return sectionCitation;
    }

    /**
     * Sets the value of the sectionCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSectionCitation(String value) {
        this.sectionCitation = value;
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link RequirementCategories }
     *     
     */
    public RequirementCategories getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequirementCategories }
     *     
     */
    public void setCategories(RequirementCategories value) {
        this.categories = value;
    }

    /**
     * Gets the value of the typeOfCompliance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfCompliance() {
        return typeOfCompliance;
    }

    /**
     * Sets the value of the typeOfCompliance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfCompliance(String value) {
        this.typeOfCompliance = value;
    }

    /**
     * Gets the value of the tfe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTFE() {
        return tfe;
    }

    /**
     * Sets the value of the tfe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTFE(String value) {
        this.tfe = value;
    }

    /**
     * Gets the value of the violationSeverityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViolationSeverityLevel() {
        return violationSeverityLevel;
    }

    /**
     * Sets the value of the violationSeverityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViolationSeverityLevel(String value) {
        this.violationSeverityLevel = value;
    }

    /**
     * Gets the value of the violationRiskFactor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViolationRiskFactor() {
        return violationRiskFactor;
    }

    /**
     * Sets the value of the violationRiskFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViolationRiskFactor(String value) {
        this.violationRiskFactor = value;
    }

    /**
     * Gets the value of the tier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTier() {
        return tier;
    }

    /**
     * Sets the value of the tier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTier(String value) {
        this.tier = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYear(String value) {
        this.year = value;
    }

    /**
     * Gets the value of the impactAndPenalties property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpactAndPenalties() {
        return impactAndPenalties;
    }

    /**
     * Sets the value of the impactAndPenalties property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpactAndPenalties(String value) {
        this.impactAndPenalties = value;
    }

    /**
     * Gets the value of the penaltiesForNonCompliance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenaltiesForNonCompliance() {
        return penaltiesForNonCompliance;
    }

    /**
     * Sets the value of the penaltiesForNonCompliance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenaltiesForNonCompliance(String value) {
        this.penaltiesForNonCompliance = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequency(String value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the startAfter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartAfter() {
        return startAfter;
    }

    /**
     * Sets the value of the startAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartAfter(String value) {
        this.startAfter = value;
    }

    /**
     * Gets the value of the dueAfter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueAfter() {
        return dueAfter;
    }

    /**
     * Sets the value of the dueAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueAfter(String value) {
        this.dueAfter = value;
    }

    /**
     * Gets the value of the nextScheduleDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextScheduleDate() {
        return nextScheduleDate;
    }

    /**
     * Sets the value of the nextScheduleDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextScheduleDate(String value) {
        this.nextScheduleDate = value;
    }

    /**
     * Gets the value of the relationships property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipType }
     *     
     */
    public RelationshipType getRelationships() {
        return relationships;
    }

    /**
     * Sets the value of the relationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipType }
     *     
     */
    public void setRelationships(RelationshipType value) {
        this.relationships = value;
    }

}
