//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.19 at 02:21:49 PM IST 
//


package com.metricstream.systemi.rga.grcobject.jaxb.aoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AOCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AOCType">
 *   &lt;complexContent>
 *     &lt;extension base="{}CommonFieldsType">
 *       &lt;sequence>
 *         &lt;element name="aocClassificationType" type="{}ListOfValues" minOccurs="0"/>
 *         &lt;element name="Relationships" type="{}RelationshipType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AOCType", propOrder = {
    "aocClassificationType",
    "relationships"
})
public class AOCType
    extends CommonFieldsType
{

    protected ListOfValues aocClassificationType;
    @XmlElement(name = "Relationships")
    protected RelationshipType relationships;

    /**
     * Gets the value of the aocClassificationType property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfValues }
     *     
     */
    public ListOfValues getAocClassificationType() {
        return aocClassificationType;
    }

    /**
     * Sets the value of the aocClassificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfValues }
     *     
     */
    public void setAocClassificationType(ListOfValues value) {
        this.aocClassificationType = value;
    }

    /**
     * Gets the value of the relationships property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipType }
     *     
     */
    public RelationshipType getRelationships() {
        return relationships;
    }

    /**
     * Sets the value of the relationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipType }
     *     
     */
    public void setRelationships(RelationshipType value) {
        this.relationships = value;
    }

}
