//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.19 at 02:25:45 PM IST 
//


package com.metricstream.systemi.rga.grcobject.jaxb.requirement;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Datapacket }
     * 
     */
    public Datapacket createDatapacket() {
        return new Datapacket();
    }

    /**
     * Create an instance of {@link MessageHeaderType }
     * 
     */
    public MessageHeaderType createMessageHeaderType() {
        return new MessageHeaderType();
    }

    /**
     * Create an instance of {@link DataLinesType }
     * 
     */
    public DataLinesType createDataLinesType() {
        return new DataLinesType();
    }

    /**
     * Create an instance of {@link ListOfValues }
     * 
     */
    public ListOfValues createListOfValues() {
        return new ListOfValues();
    }

    /**
     * Create an instance of {@link ApproverType }
     * 
     */
    public ApproverType createApproverType() {
        return new ApproverType();
    }

    /**
     * Create an instance of {@link CommonFieldsType }
     * 
     */
    public CommonFieldsType createCommonFieldsType() {
        return new CommonFieldsType();
    }

    /**
     * Create an instance of {@link RQMTRelatedType }
     * 
     */
    public RQMTRelatedType createRQMTRelatedType() {
        return new RQMTRelatedType();
    }

    /**
     * Create an instance of {@link RelationshipType }
     * 
     */
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

    /**
     * Create an instance of {@link RQTType }
     * 
     */
    public RQTType createRQTType() {
        return new RQTType();
    }

    /**
     * Create an instance of {@link RequirementCategories }
     * 
     */
    public RequirementCategories createRequirementCategories() {
        return new RequirementCategories();
    }

    /**
     * Create an instance of {@link RelatedType }
     * 
     */
    public RelatedType createRelatedType() {
        return new RelatedType();
    }

}
