//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 03:06:07 PM IST 
//


package com.metricstream.systemi.rga.rdc.pojo.rib;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for AlertEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlertEntity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entityId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rdcUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="source" type="{http://www.rdc.com/batch/rdc_rib.xsd}AlertEntitySource"/>
 *         &lt;element name="events" type="{http://www.rdc.com/batch/rdc_rib.xsd}AlertEntityEvents"/>
 *         &lt;element name="aliases" type="{http://www.rdc.com/batch/rdc_rib.xsd}AlertEntityAliases" minOccurs="0"/>
 *         &lt;element name="addresses" type="{http://www.rdc.com/batch/rdc_rib.xsd}AlertEntityAddresses" minOccurs="0"/>
 *         &lt;element name="dobs" type="{http://www.rdc.com/batch/rdc_rib.xsd}AlertEntityDobs" minOccurs="0"/>
 *         &lt;element name="attributes" type="{http://www.rdc.com/batch/rdc_rib.xsd}AlertEntityAttributes" minOccurs="0"/>
 *         &lt;element name="riskScore" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="alertNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cvipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recentEvents" type="{http://www.rdc.com/batch/rdc_rib.xsd}AlertEntityEvents" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='http://www.rdc.com/batch/rdc_rib.xsd' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlertEntity", propOrder = {
    "entityId",
    "entityType",
    "entityName",
    "rdcUrl",
    "source",
    "events",
    "aliases",
    "addresses",
    "dobs",
    "attributes",
    "riskScore",
    "alertNote",
    "systemId",
    "cvipCode",
    "recentEvents",
    "any"
})
public class AlertEntity {

    @XmlElement(required = true)
    protected String entityId;
    @XmlElement(required = true)
    protected String entityType;
    @XmlElement(required = true)
    protected String entityName;
    @XmlElement(required = true)
    protected String rdcUrl;
    @XmlElement(required = true)
    protected AlertEntitySource source;
    @XmlElement(required = true)
    protected AlertEntityEvents events;
    protected AlertEntityAliases aliases;
    protected AlertEntityAddresses addresses;
    protected AlertEntityDobs dobs;
    protected AlertEntityAttributes attributes;
    protected Integer riskScore;
    protected String alertNote;
    @XmlElement(required = true)
    protected String systemId;
    protected String cvipCode;
    protected AlertEntityEvents recentEvents;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the entityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * Sets the value of the entityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityId(String value) {
        this.entityId = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityType(String value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the entityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * Sets the value of the entityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityName(String value) {
        this.entityName = value;
    }

    /**
     * Gets the value of the rdcUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRdcUrl() {
        return rdcUrl;
    }

    /**
     * Sets the value of the rdcUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRdcUrl(String value) {
        this.rdcUrl = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link AlertEntitySource }
     *     
     */
    public AlertEntitySource getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertEntitySource }
     *     
     */
    public void setSource(AlertEntitySource value) {
        this.source = value;
    }

    /**
     * Gets the value of the events property.
     * 
     * @return
     *     possible object is
     *     {@link AlertEntityEvents }
     *     
     */
    public AlertEntityEvents getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertEntityEvents }
     *     
     */
    public void setEvents(AlertEntityEvents value) {
        this.events = value;
    }

    /**
     * Gets the value of the aliases property.
     * 
     * @return
     *     possible object is
     *     {@link AlertEntityAliases }
     *     
     */
    public AlertEntityAliases getAliases() {
        return aliases;
    }

    /**
     * Sets the value of the aliases property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertEntityAliases }
     *     
     */
    public void setAliases(AlertEntityAliases value) {
        this.aliases = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link AlertEntityAddresses }
     *     
     */
    public AlertEntityAddresses getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertEntityAddresses }
     *     
     */
    public void setAddresses(AlertEntityAddresses value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the dobs property.
     * 
     * @return
     *     possible object is
     *     {@link AlertEntityDobs }
     *     
     */
    public AlertEntityDobs getDobs() {
        return dobs;
    }

    /**
     * Sets the value of the dobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertEntityDobs }
     *     
     */
    public void setDobs(AlertEntityDobs value) {
        this.dobs = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link AlertEntityAttributes }
     *     
     */
    public AlertEntityAttributes getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertEntityAttributes }
     *     
     */
    public void setAttributes(AlertEntityAttributes value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the riskScore property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRiskScore() {
        return riskScore;
    }

    /**
     * Sets the value of the riskScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRiskScore(Integer value) {
        this.riskScore = value;
    }

    /**
     * Gets the value of the alertNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertNote() {
        return alertNote;
    }

    /**
     * Sets the value of the alertNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertNote(String value) {
        this.alertNote = value;
    }

    /**
     * Gets the value of the systemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemId(String value) {
        this.systemId = value;
    }

    /**
     * Gets the value of the cvipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCvipCode() {
        return cvipCode;
    }

    /**
     * Sets the value of the cvipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCvipCode(String value) {
        this.cvipCode = value;
    }

    /**
     * Gets the value of the recentEvents property.
     * 
     * @return
     *     possible object is
     *     {@link AlertEntityEvents }
     *     
     */
    public AlertEntityEvents getRecentEvents() {
        return recentEvents;
    }

    /**
     * Sets the value of the recentEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertEntityEvents }
     *     
     */
    public void setRecentEvents(AlertEntityEvents value) {
        this.recentEvents = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
