//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 03:06:07 PM IST 
//


package com.metricstream.systemi.rga.rdc.pojo.rib;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for InquiryDisposition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InquiryDisposition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reviewStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inquiryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="portfolioMonitoring" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="monitoredSince" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="trackingId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reportingId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inquiryNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inquiryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="alert" type="{http://www.rdc.com/batch/rdc_rib.xsd}Alert" minOccurs="0"/>
 *         &lt;element name="legacyIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='http://www.rdc.com/batch/rdc_rib.xsd' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InquiryDisposition", propOrder = {
    "reviewStatus",
    "inquiryId",
    "portfolioMonitoring",
    "monitoredSince",
    "trackingId",
    "reportingId",
    "inquiryNotes",
    "inquiryType",
    "name",
    "address1",
    "city",
    "province",
    "postalCode",
    "country",
    "dateOfBirth",
    "alert",
    "legacyIdentifier",
    "any"
})
public class InquiryDisposition {

    @XmlElement(required = true)
    protected String reviewStatus;
    @XmlElement(required = true)
    protected String inquiryId;
    protected boolean portfolioMonitoring;
    protected String monitoredSince;
    @XmlElement(required = true)
    protected String trackingId;
    protected String reportingId;
    protected String inquiryNotes;
    @XmlElement(required = true)
    protected String inquiryType;
    @XmlElement(required = true)
    protected String name;
    protected String address1;
    protected String city;
    protected String province;
    protected String postalCode;
    protected String country;
    protected String dateOfBirth;
    protected Alert alert;
    protected String legacyIdentifier;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    
    public String toString(){
    	StringBuilder sb = new StringBuilder("Name=" + name + "  inquiry[id="+inquiryId+"; type="+inquiryType+ "; notes=" + inquiryNotes);
    	sb.append("  ;DoB=" + dateOfBirth + "@" + address1 +"/"+province+"/"+ postalCode+"/"+country);
    	sb.append("  ;IDs[track="+trackingId+ "; reporting=" + reportingId+ "; legacy=" + legacyIdentifier);
    	sb.append("  ;Alert= " + alert + "\n");
    	return sb.toString();
    }
    
    /**
     * Gets the value of the reviewStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewStatus() {
        return reviewStatus;
    }

    /**
     * Sets the value of the reviewStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewStatus(String value) {
        this.reviewStatus = value;
    }

    /**
     * Gets the value of the inquiryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInquiryId() {
        return inquiryId;
    }

    /**
     * Sets the value of the inquiryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInquiryId(String value) {
        this.inquiryId = value;
    }

    /**
     * Gets the value of the portfolioMonitoring property.
     * 
     */
    public boolean isPortfolioMonitoring() {
        return portfolioMonitoring;
    }

    /**
     * Sets the value of the portfolioMonitoring property.
     * 
     */
    public void setPortfolioMonitoring(boolean value) {
        this.portfolioMonitoring = value;
    }

    /**
     * Gets the value of the monitoredSince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonitoredSince() {
        return monitoredSince;
    }

    /**
     * Sets the value of the monitoredSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonitoredSince(String value) {
        this.monitoredSince = value;
    }

    /**
     * Gets the value of the trackingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingId() {
        return trackingId;
    }

    /**
     * Sets the value of the trackingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingId(String value) {
        this.trackingId = value;
    }

    /**
     * Gets the value of the reportingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingId() {
        return reportingId;
    }

    /**
     * Sets the value of the reportingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingId(String value) {
        this.reportingId = value;
    }

    /**
     * Gets the value of the inquiryNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInquiryNotes() {
        return inquiryNotes;
    }

    /**
     * Sets the value of the inquiryNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInquiryNotes(String value) {
        this.inquiryNotes = value;
    }

    /**
     * Gets the value of the inquiryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInquiryType() {
        return inquiryType;
    }

    /**
     * Sets the value of the inquiryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInquiryType(String value) {
        this.inquiryType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the province property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvince() {
        return province;
    }

    /**
     * Sets the value of the province property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvince(String value) {
        this.province = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the alert property.
     * 
     * @return
     *     possible object is
     *     {@link Alert }
     *     
     */
    public Alert getAlert() {
        return alert;
    }

    /**
     * Sets the value of the alert property.
     * 
     * @param value
     *     allowed object is
     *     {@link Alert }
     *     
     */
    public void setAlert(Alert value) {
        this.alert = value;
    }

    /**
     * Gets the value of the legacyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegacyIdentifier() {
        return legacyIdentifier;
    }

    /**
     * Sets the value of the legacyIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegacyIdentifier(String value) {
        this.legacyIdentifier = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
