//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 03:06:07 PM IST 
//


package com.metricstream.systemi.rga.rdc.pojo.rib;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for ResponseHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="firmNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datetime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inputFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="responseType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="batchType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="batchId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="batchDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inquiryCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="gridMatchCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="alertCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='http://www.rdc.com/batch/rdc_rib.xsd' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseHeader", propOrder = {
    "version",
    "firmNumber",
    "datetime",
    "inputFileName",
    "responseType",
    "batchType",
    "batchId",
    "batchDate",
    "inquiryCount",
    "gridMatchCount",
    "alertCount",
    "any"
})
public class ResponseHeader {

    @XmlElement(required = true)
    protected String version;
    @XmlElement(required = true)
    protected String firmNumber;
    @XmlElement(required = true)
    protected String datetime;
    protected String inputFileName;
    @XmlElement(required = true)
    protected String responseType;
    @XmlElement(required = true)
    protected String batchType;
    @XmlElement(required = true)
    protected String batchId;
    @XmlElement(required = true)
    protected String batchDate;
    protected Integer inquiryCount;
    protected Integer gridMatchCount;
    protected Integer alertCount;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    
    public String toString(){
    	StringBuilder sb = new StringBuilder();
    	sb.append("Input {Firm#: " + firmNumber + "; date: " + datetime + "file=" + inputFileName +"} --- responseType= "+ responseType + ";");
    	sb.append("Batch(id=" + batchId+"; Type=" + batchType + " Date=" + batchDate + ")");
    	sb.append("Counts[inquiries="+ inquiryCount + "; Matches=" + gridMatchCount + "]" + "\n Alerts=" + alertCount);
    	
    	return sb.toString();
    }
    
    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the firmNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirmNumber() {
        return firmNumber;
    }

    /**
     * Sets the value of the firmNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirmNumber(String value) {
        this.firmNumber = value;
    }

    /**
     * Gets the value of the datetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatetime() {
        return datetime;
    }

    /**
     * Sets the value of the datetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatetime(String value) {
        this.datetime = value;
    }

    /**
     * Gets the value of the inputFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputFileName() {
        return inputFileName;
    }

    /**
     * Sets the value of the inputFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputFileName(String value) {
        this.inputFileName = value;
    }

    /**
     * Gets the value of the responseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseType() {
        return responseType;
    }

    /**
     * Sets the value of the responseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseType(String value) {
        this.responseType = value;
    }

    /**
     * Gets the value of the batchType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchType() {
        return batchType;
    }

    /**
     * Sets the value of the batchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchType(String value) {
        this.batchType = value;
    }

    /**
     * Gets the value of the batchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * Sets the value of the batchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchId(String value) {
        this.batchId = value;
    }

    /**
     * Gets the value of the batchDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchDate() {
        return batchDate;
    }

    /**
     * Sets the value of the batchDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchDate(String value) {
        this.batchDate = value;
    }

    /**
     * Gets the value of the inquiryCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInquiryCount() {
        return inquiryCount;
    }

    /**
     * Sets the value of the inquiryCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInquiryCount(Integer value) {
        this.inquiryCount = value;
    }

    /**
     * Gets the value of the gridMatchCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGridMatchCount() {
        return gridMatchCount;
    }

    /**
     * Sets the value of the gridMatchCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGridMatchCount(Integer value) {
        this.gridMatchCount = value;
    }

    /**
     * Gets the value of the alertCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAlertCount() {
        return alertCount;
    }

    /**
     * Sets the value of the alertCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAlertCount(Integer value) {
        this.alertCount = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
