//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 03:06:07 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.rdc.com/batch/rdc_rib.xsd")
package com.metricstream.systemi.rga.rdc.pojo.rib;
